### ISSUE TITLE
Matrix.GetHashCode

### ISSUE THREAD

**Issue by nsp** [moserware/Skills#1]
Matrix.GetHashCode() function does not return the same value for all Matrices that are equal. For example, the following fails on the last line (one more 0 and it passes). Consider somehow rounding each double before putting it in the hash.

```
var a = new SquareMatrix(1, 2.00000000000001,
                                 3, 4);

var b = new SquareMatrix(1, 2,
                                 3, 4);

Assert.IsTrue(a == b);
Assert.AreEqual(a, b);
Assert.AreEqual(a.GetHashCode(), b.GetHashCode());
```

**Comment by moserware** [comment]
Thanks, I fixed this in  9bc97fa1c332249ea2eefc775c221ad82fe88756
