### ISSUE TITLE
AttributeError: 'module' object has no attribute 'EloRating'

### ISSUE THREAD

**Issue by mattobrien415** [moserware/Skills#10]
Can't seem to access the `EloRating` object.

```
import skills as s
s.EloRating(1200, 32)
```

returns
`AttributeError: 'module' object has no attribute 'EloRating'`

Nevermind I figured it out...thanks!!

**Comment by anon-cto** [comment]
Skills is the module name.  EloRating is the class.  You don't need to specify skills.EloRating.  You also can't create an object in that way.  To create an EloRating object, try: EloRating eloRating = new EloRating(1200.0);

**Comment by mobbSF** [comment]
I'm sorry, I changed a small typo above. :)

`eloRating = new EloRating(1200.0); `is syntactically incorrect, no?

**Comment by mattobrien415** [comment]
Thanks!
