### ISSUE TITLE
Program never halts with non-zero draw probability and buggy input

### ISSUE THREAD

**Issue by dlh** [moserware/Skills#7]
# Program never halts with non-zero draw probability and buggy input

I've created a [small test case for this bug/issue](https://gist.github.com/1290559).

In one of my projects I stumbled on some input that would cause TrueSkillCalculator.CalculateNewRatings() to never return. The input was actually the result of a bug in my code, but I expect the test case program to either return a result or throw an exception.

The issue appears related to using a DrawProbability value greater than 0.

Software versions:

```
$ mono --version
Mono JIT compiler version 2.10.6 (tarball Fri Sep 16 00:13:06 EDT 2011)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       normal
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          debugger softdebug 
    LLVM:          yes(2.9svn-mono)
    GC:            Included Boehm (with typed GC)
$ uname -a
Darwin queue.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386
```

**Comment by Zannick** [comment]
Did you ever find a workaround or resolution to this?
